spring.application.name=analyticsapi
spring.datasource.url=jdbc:postgresql://localhost:5432/analyticsdb
spring.datasource.username=postgres
spring.datasource.password=admin

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.jdbc.batch_size=1000
server.port=8080
